# Generated by Django 2.2.1 on 2019-06-17 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='', max_length=200)),
                ('mName', models.CharField(blank=True, max_length=200, null=True)),
                ('lName', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='music_era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_era', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('end_era', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='musical_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='scale_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='musical_piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('comp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_blog.composer')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_blog.scale')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_blog.scale_type')),
            ],
        ),
        migrations.CreateModel(
            name='list_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_blog.list')),
            ],
        ),
    ]
