# Generated by Django 2.2.1 on 2019-06-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0002_composer_list_list_content_music_era_musical_genre_musical_piece_scale_scale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_content',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_blog.musical_piece'),
        ),
    ]
