# Generated by Django 2.2.1 on 2019-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0003_list_content_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_era',
            name='bc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='music_era',
            name='end_era',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
