# Generated by Django 2.2.1 on 2019-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0004_auto_20190617_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musical_piece',
            old_name='comp',
            new_name='composer',
        ),
        migrations.RenameField(
            model_name='musical_piece',
            old_name='type',
            new_name='scale_type',
        ),
        migrations.AddField(
            model_name='musical_piece',
            name='piece_number',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='musical_piece',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
