# Generated by Django 2.2.1 on 2019-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0005_auto_20190617_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='catalogue_symbol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='composer',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
