# Generated by Django 2.2.1 on 2019-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0008_auto_20190617_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='music_blog/media/composer_pics'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='music_blog/media/profile_pics'),
        ),
    ]
