# Generated by Django 2.2.1 on 2019-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0009_auto_20190619_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical_piece',
            name='fingerprint_id',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
